### ISSUE TITLE
Font for zh-tw

### ISSUE THREAD

**Issue by cheetosysst** [simba-fs/slides#1]
給做參考，這是我覺得看起來比較舒服的組合
```css
* {
    font-family: "Helvetica", "Arial","LiHei Pro","黑體-繁","微軟正黑體", sans-serif;
}
```
[Google Fonts](https://fonts.google.com/) 找一下
